name: github pages

# Runs on
# - there are changes on 'docs/gh-pages/**' or '.github/workflows/gh-pages.yml' and push to the main branch
# - release tags 
on:
  push:
    branches:
      - main 
    paths:
      - docs/gh-pages/**
      - .github/workflows/gh-pages.yml
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        working-directory: docs/gh-pages/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/gh-pages/public/